
services:
  postgres:
    image: postgres:15
    container_name: blog-postgres-db
    environment:
      POSTGRES_USER: devOliveira
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: